import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  container: {
    backgroundColor: 'rgba(247,247,255,1)',
    flex: 1,
  },
  headerContainer: {
    backgroundColor: 'white',
    paddingHorizontal: 30,
  },
  block1: {
    marginVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconContainerLeft: {
    width: 40,
    height: 40,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'rgba(238,243,247,1)',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 5,
    paddingVertical: 4,
  },
  iconStyle1: {
    width: 10,
    height: 20,
    backgroundColor: 'rgba(46,208,251,1)',
    borderBottomEndRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    marginTop: 5,
  },
  iconStyle2: {
    width: 10,
    height: 20,
    backgroundColor: 'rgba(52,133,239,1)',
    borderBottomEndRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  iconContainerRight: {
    width: 40,
    height: 40,
    borderColor: 'rgba(52,133,239,1)',
    borderWidth: 2,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: 'rgba(52,133,239,1)',
  },
  iconStyle3: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  plusStyle: {
    fontSize: 30,
    textAlign: 'center',
    color: 'white',
    flex: 1,
  },
  titleContainer: {
    marginVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  txtStyle: {
    fontSize: 30,
    fontWeight: 'bold',
  },
  titleRightContainer: {
    width: 80,
    height: 40,
    borderColor: 'rgba(247,247,255,1)',
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: 'rgba(247,247,255,1)',
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 4,
  },
  block2: {
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  block3: {
    justifyContent: 'space-between',
    alignContent: 'space-between',
    flex: 1,
    marginVertical: 8,
  },
  block4: {
    width: 20,
    height: 8,
    backgroundColor: 'rgba(52,133,239,1)',
  },
  block5: {
    width: 20,
    height: 8,
    backgroundColor: 'rgba(52,133,239,1)',
  },
  block6: {
    //flex:1,
    width: 2,
    height: 20,
    backgroundColor: 'rgba(222,219,229,1)',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },

  block7: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },

  block8: {
    width: 20,
    height: 20,
    backgroundColor: 'rgba(189,199,235,1)',
    marginRight: 4,
  },

  block9: {
    width: 5,
    height: 20,
    backgroundColor: 'rgba(189,199,235,1)',
  },
  tabView: {
    backgroundColor: 'white',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    borderColor: 'white',
    borderWidth: 2,
    top: -3,
  },
  containerStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  TextStyle: {
    fontSize: 30,
    fontWeight: 'bold',
  },
  ViewStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 300,
    height: 300,
    borderRadius: 15,
    borderWidth: 2,
    backgroundColor: 'rgba(247,247,254,1)',
    borderColor: 'rgba(215,215,216,1)',
  },
});
